# Generated by Django 3.1.1 on 2020-10-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_asset_assetgroup_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='value',
        ),
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='remarks',
            field=models.CharField(default='无', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='value_origin',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='asset',
            name='value_worth',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
