# Generated by Django 3.1.1 on 2020-10-20 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201020_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='value',
            new_name='value_origin',
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.assetstatus'),
        ),
    ]
