# Generated by Django 3.1.1 on 2020-10-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201020_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='status',
        ),
    ]
