# Generated by Django 3.1.2 on 2020-10-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201020_1638'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asset_status',
            new_name='Assetstatus',
        ),
    ]
