# Generated by Django 3.1.2 on 2020-10-20 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201020_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.assetstatus'),
        ),
    ]
