# Generated by Django 3.1.2 on 2020-10-20 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='use_year',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date',
            field=models.DateField(default=datetime.date(2020, 10, 20)),
        ),
        migrations.AlterField(
            model_name='asset',
            name='value_worth',
            field=models.PositiveIntegerField(default=models.PositiveIntegerField(default=1)),
        ),
    ]
