# Generated by Django 3.1.2 on 2020-10-20 10:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201020_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='belongs_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 20, 18, 30, 20, 385983)),
        ),
    ]
