# Generated by Django 3.1.2 on 2020-10-20 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201020_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 10, 20, 18, 39, 56, 482889)),
        ),
    ]
