# Generated by Django 3.1.2 on 2020-10-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201020_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
    ]
