# Generated by Django 3.1.2 on 2020-10-21 11:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201020_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(api.models.get_default_asset_group), to='api.assetgroup'),
        ),
        migrations.AlterField(
            model_name='assetgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(api.models.get_default_asset_group), to='api.assetgroup'),
        ),
    ]
