# Generated by Django 3.1.2 on 2020-10-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20201027_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='belongs_to_pending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff'),
        ),
    ]
