# Generated by Django 3.1.2 on 2020-11-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_department_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
