# Generated by Django 3.1.2 on 2020-11-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20201103_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
